# Generated by Django 3.2.9 on 2021-11-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('order_status', models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('Stored', 'Stored'), ('Send', 'Send')], max_length=11)),
                ('warehouse_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='storeApp.warehouse')),
            ],
        ),
    ]
